### PR TITLE
removing windows partial new line token from the version

### LINKED ISSUE #727: Invalid header field value "1.7.0\r" for key Meroxa-Cli-App-Version;"
**Describe the bug**  

User receives an error when attempting to deploy turbine-py app on a Windows Machine.

> "Error: Get "https://api.meroxa.io/v1/resources/gdatabucket": net/http: invalid header field value "1.7.0\r" for key Meroxa-Cli-App-Version;"

**Machine:**  

 - OS: Windows
 - CLI Version meroxa/2.18.0 windows/amd64
 - turbine-py 1.7.0

**To Reproduce**  
* Install turbine-py and Meroxa CLI on Windows machine.
* Create Turbine app
* Attempt to `meroxa apps deploy`

**Expected behavior**  
The app should deploy

**Screenshots**  
image

**Additional context**

### PR DESCRIPTION
**Pull request by nassor**
## Description of change

Fixes #727 

## Type of change

- [X]  Bug fix

### CODE REVIEW

**Review by dianadoherty — APPROVED** [review]

File: cmd/meroxa/turbine/python/version.go [hunk 1]
```diff
@@ -24,7 +24,8 @@ func (t *turbinePyCLI) GetVersion(_ context.Context) (string, error) {
 	if err != nil {
 		// For versions <= v1.6.1
 		version = string(output)
-		version = strings.TrimSpace(version)
+		version = strings.TrimSpace(version)  // it will remove tab '\t' and new lines '\n' as well
+		version = strings.Trim(version, "\r") // windows: removing part of windows new line
```
Comment (maha-hajja) [inline cmd/meroxa/turbine/python/version.go:28]: nitpick:
```suggestion
		version = strings.Trim(version, "\r") // windows: remove carriage returns
```

**Review by jayjayjpg — APPROVED** [review]
This reads great, thank you for the super quick fix and triage! :sparkles:

File: cmd/meroxa/turbine/utils.go [hunk 2]
```diff
@@ -280,12 +280,14 @@ func GetGitBranch(appPath string) (string, error) {
 }
 
 func GetTurbineResponseFromOutput(output string) (string, error) {
-	r := regexp.MustCompile("turbine-response: ([^\n]*)")
+	r := regexp.MustCompile("turbine-response: ([^\r\n]*)")
 	match := r.FindStringSubmatch(output)
 	if match == nil || len(match) < 2 {
 		return "", fmt.Errorf("output is formatted unexpectedly")
 	}
```
Comment (simonl2002) [inline cmd/meroxa/turbine/utils.go:287]: I didn't make these changes but it feels like given what's being done in version.go `GetVersion` function, it feels like this should NOT actually be returning an error. Instead we should properly handle both forms of the response output here rather than relying on the caller to clean things up.
