### PR TITLE
Validate environment exists before turbine app is deployed

### LINKED ISSUE #621: [Env: cli] Descriptive error when creating an app in a non existing env
## Context 

When creating an app in an environment that doesn't exist, we don't get a good error message.

```
meroxa apps deploy --env bad-aws
Validating your app.json...
	✔ Checked your language is "ruby"
	✔ Checked your application name is "test-rb"
Checking for uncommitted changes...
	✔ No uncommitted changes!
Error: could not find environment
```

## Acceptance

- [ ] Ensure API has a clearer message for when an app fails to deploy in an environment

### PR DESCRIPTION
**Pull request by lyuboxa**
## Description of change

Ensure environment exists when the `--env` flag is specified before the turbine deploy begins.

Fixes #621 

## Type of change

- [x]  New feature
- [ ]  Bug fix
- [x]  Refactor
- [ ]  Documentation

## How was this tested?

- [x]  Unit Tests
- [ ]  Tested in staging
- [ ]  Tested in minikube

## Demo

| before | after |
|--------|-------|
|||

### CODE REVIEW

**Review by dianadoherty — APPROVED** [review]

File: cmd/meroxa/root/apps/deploy.go [hunk 1]
```diff
@@ -5,15 +5,14 @@ Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at
 
-    http://www.apache.org/licenses/LICENSE-2.0
+	http://www.apache.org/licenses/LICENSE-2.0
```
Comment (janelletavares) [inline cmd/meroxa/root/apps/deploy.go:8]: intentional?

File: cmd/meroxa/root/apps/deploy.go [hunk 2]
```diff
@@ -66,6 +66,22 @@ type deployApplicationClient interface {
...
+}
+
+func (e *environment) nameOrUUID() string {
+	switch {
+	case e.UUID != "":
+		return e.UUID
+	case e.Name != "":
+		return e.Name
+	default:
+		panic("bad state: name or uuid should be present")
```
Comment (janelletavares) [inline cmd/meroxa/root/apps/deploy.go:81]: i prefer not to panic because it feels like a bad customer experience if the CLI were to ever actually hit this

Comment (lyuboxa) [reply cmd/meroxa/root/apps/deploy.go:81]: I thought about this for a bit, the panic is a result of very unexpected state and we should be very vocal about it. Indeed this should never happen, but if it does.. it will blow up spectacularly, panic is used seldom, but it is used in the code base.

Comment (lyuboxa) [reply cmd/meroxa/root/apps/deploy.go:81]: Re bad customer experience, I'm not too worried, since this will grab the users attention and there is a higher chance of reporting it and engaging in a discussion.

At least this is my reasoning, let me know if you think its unreasonable.

**Review by raulb — APPROVED** [review]

File: cmd/meroxa/root/apps/deploy.go (hunk 2 above)
Comment (janelletavares) [reply cmd/meroxa/root/apps/deploy.go:82]: Sorry, I missed your responses.  I don't think customers appreciate having to sort through stacktraces.  "Error: bad state" is as clear, imho.

Comment (lyuboxa) [reply cmd/meroxa/root/apps/deploy.go:82]: Yes, but it doesn't provide context why the state is bad. Ideally we want them to file a bug.
